[WIP] Marketplace UI
galletti94/console pull request #1
Opened 2018-09-19 14:14 UTC by galletti94

- [ ] [JIRA 763](https://jira.coreos.com/browse/CONSOLE-763)
- [x] [JIRA 764](https://jira.coreos.com/browse/CONSOLE-764)
- [x] [JIRA 765](https://jira.coreos.com/browse/CONSOLE-765)

2018-09-27 13:08 UTC, SamiSousa commented on frontend/package.json
> +    "dev": "rm -rf ./public/dist/ && ts-node -O '{\"module\":\"commonjs\"}' ./node_modules/.bin/webpack --mode development --watch --watch-pull --progress",
We can leave this the way it was. The issue was not having enough watchers, and they've already added that to the readme.

2018-09-27 13:55 UTC, SamiSousa requested changes
Overall I think it's pretty good! There's a couple things with setState that should be changed, then run the linter.

2018-09-27 13:55 UTC, SamiSousa commented on frontend/public/components/marketplace/catalog-tiles.jsx
> +import { interpolateMagma } from 'd3';
I don't think this is used on this page. We should run these changes through a linter / automated cleanup.

2018-09-27 13:55 UTC, SamiSousa commented on frontend/public/components/marketplace/catalog-tiles.jsx
> +    if (!showAll || category.id === showAll) {
I'm not sure I understand this if statement, could you explain?

2018-09-27 13:55 UTC, SamiSousa commented on frontend/public/components/marketplace/catalog-tiles.jsx
> +      <div>
I think using <React.Fragment> in render functions might be cleaner, since the result doesn't add extra divs.

2018-09-27 13:55 UTC, SamiSousa commented on frontend/public/components/marketplace/modeless-manager.jsx
> +    });
This should be `this.setState( prevState => { showOverlay: !prevState.showOverlay });`
React docs says it's more reliable that way.

2018-09-27 13:55 UTC, SamiSousa commented on frontend/public/components/marketplace/modeless-manager.jsx
> +            <div style={{ marginTop: '30px', width: '100%', height: '100%'}}>
At some point we should consolidate our styles into a css file

2018-09-27 13:55 UTC, SamiSousa commented on frontend/public/components/marketplace/toolbar.jsx
> +    this.setState({ isSortAscending: !isSortAscending });
Use `this.setState(prevState => {...});`

2018-09-27 13:55 UTC, SamiSousa commented on frontend/public/components/marketplace/vertical-tabs.jsx
> +      activeTabId === 'two';
Not sure what `activeTabId` is trying to accomplish

2018-09-27 13:55 UTC, SamiSousa commented on setup.sh
> +#!/usr/bin/env bash
Remember to remove this (!)

2018-09-28 18:59 UTC, tlwu2013 commented
Could you post the latest screenshots here for review?  Thanks!

Based on the screenshots in https://github.com/openshift/console/pull/596, a couple of things:
1. Marketplace UI doesn't have `Project/Namespace bar` at the top of the screen.
2. Generic template spacing / padding (see redlines attached below)
3. "Search box" on the top-right corner is for "advanced search", so it's not ready yet and can be taken out.
4. "Subscription" page should be an embeded page instead of living on the sidebar.

Here's the redlines for the tile view for reference:
![kamp__tile-view__responsive_redline](https://user-images.githubusercontent.com/5903705/46227517-4b023c00-c314-11e8-98f8-a1b08ab6367e.png)

And see the left-most column of the flow diagram for reference:
![v9 8__ admin _kamp-ui olm-ui-tweaks](https://user-images.githubusercontent.com/5903705/46228012-b39de880-c315-11e8-948c-3dbe1d5c9910.png)

2019-02-21 18:56 UTC, closed without merging